# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'Deploy to Azure App Service'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env: 
  AZURE_HEATEXCHANGER_WEBAPP_PATH: '.'
  AZURE_HEATEXCHANGER_WEBAPP_NAME: HeatExchangeMonitor


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
    - run: dotnet publish -c Release -o '${{ env.AZURE_HEATEXCHANGER_WEBAPP_PATH }}/myapp'

    - name: Deploy
      uses: Azure/webapps-deploy@v2.2.17
      with:
        app-name: ${{ AZURE_HEATEXCHANGER_WEBAPP_NAME }}
        slot-name: 'development'
        publish-profile: ${{ secrets.AZURE_HEATEXCHANGER_WEBAPP }}
        package: '${{ env.AZURE_HEATEXCHANGER_WEBAPP_PATH }}/myapp'
    
